mutation createUser(
  $username: String!
  $password: String!
  # $firstName: String!
  # $lastName: String!
  $email: String!
) {
  createUser(
    username: $username
    password: $password
    # firstName: $firstName
    # lastName: $lastName
    email: $email
  ) {
    success
    details
    token
    refreshToken
  }
}
