query userPlaylistsData($offset: Int!) {
  userPlaylistsData(offset: $offset) {
    success
    details
    owner {
      id
      name
      href
    }
    playlists {
      id
      name
      description
      href
      image
    }
    lastPage
  }
}
